/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessSites: typeof import('./../components/accessSites.vue')['default']
    AppLogo: typeof import('./../components/AppLogo.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    DataView: typeof import('primevue/dataview')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LookupPanel: typeof import('./../components/LookupPanel.vue')['default']
    Message: typeof import('primevue/message')['default']
    OverlayHeader: typeof import('./../components/OverlayHeader.vue')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    WordItem: typeof import('./../components/WordItem.vue')['default']
    WordListPanel: typeof import('./../components/WordListPanel.vue')['default']
  }
}
